# Removed obsolete version attribute as per Docker Compose V2

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "9080:9080"
    depends_on:
      db:
        condition: service_healthy
      etcd:
        condition: service_healthy
    environment:
      APISIX_ETCD_HOST: etcd:2379
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: ${POSTGRES_USER:-user}
      PG_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PG_DBNAME: ${POSTGRES_DB:-solcalc}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080"]
      interval: 30s
      timeout: 10s
      retries: 3
    
      

  calculation-service:
    build: ./services/calculation-service
    ports:
      - "5001:5001"  # Expose for debugging/direct access
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env # Assuming .env contains DATABASE_URL for calculation-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  pdf-generation-service:
    build: ./services/pdf-generation-service
    ports:
      - "5002:5002"  # Expose for debugging/direct access
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env # Assuming .env contains DATABASE_URL for pdf-generation-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  payment-service:
    build: ./services/payment-service
    ports:
      - "5003:5003"  # Expose for debugging/direct access
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env # Assuming .env contains STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, DATABASE_URL etc.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./services/frontend
    ports:
      - "3000:3000"
    depends_on:
      api-gateway:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  etcd:
    image: bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-solcalc}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432" # Expose DB port for local access if needed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-solcalc}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

