version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "9080:9080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080"]
      interval: 30s
      timeout: 10s
      retries: 3

  calculation-service:
    build: ./calculation-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  pdf-generation-service:
    build: ./pdf-generation-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  payment-service:
    build: ./payment-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-solcalc}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d solcalc"]
      interval: 30s
      timeout: 10s
      retries: 3
